### PR TITLE
Fix Blitz Install

### LINKED ISSUE #3900: Blitz install stuck on "Generating file diff" in new project
### What is the problem?

`blitz install tailwind` stuck on "Generating file diff". I waited for an hour and still not done yet

### Paste all your error logs here:

```
Loaded env from /Users/macbookair/Documents/Projects/recipe-test/.env.local
Loaded env from /Users/macbookair/Documents/Projects/recipe-test/.env
✅ Installed 3 dependencies
✅ Installed 3 dependencies
✅ Successfully created postcss.config.js, tailwind.config.js
✅ Successfully created app/core/styles/index.css

+––––––––––––––––––––––––+
⎪   Import stylesheets   ⎪
+––––––––––––––––––––––––+
Imports the stylesheet we just added into your app

⠏Generating file diff...
```

### Paste all relevant code snippets here:

```
blitz install tailwind
```

### What are detailed steps to reproduce this?

1.Updated Blitz to version: 2.0.0-beta.12 with `sudo npm install -g blitz`
2. Created a new Blitz app with `blitz new`
3. `cd `into folder
4. Attempted to install tailwind with `blitz install tailwind` and stuck on "Generating file diff"

### Run `blitz -v` and paste the output here:

```
blitz -v
Blitz version: 2.0.0-beta.12 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v18.7.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 79.05 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

### Please include below any other applicable logs and screenshots that show your problem:

_No response_

### PR DESCRIPTION
**Pull request by dillonraphael**
Closes #3900

Fixes the issues with blitz install cli command by setting the correct directory & package manager when cloning a recipe from the official list.

1. Introduced the `findNodeModulesRoot` function as a starting point.
2. Check the right directory in `checkLockFileExists` to set the right package manager
3. Set the correct `chdir` when installing a recipe from github (`process.chdir(join(process.cwd(), ".."))`)

### CODE REVIEW

File: packages/blitz/src/cli/commands/install.ts [hunk 1]
```diff
@@ -62,8 +65,9 @@ const requireJSON = (file: string) => {
   return JSON.parse(require("fs-extra").readFileSync(file).toString("utf-8"))
 }
 
-const checkLockFileExists = (filename: string) => {
-  return require("fs-extra").existsSync(resolve(filename))
+const checkLockFileExists = async (filename: string) => {
+  const dotBlitz = join(await findNodeModulesRoot(process.cwd()), ".blitz")
+  return require("fs-extra").existsSync(resolve(join(dotBlitz, "..", "..", filename)))
```
Comment (beerose) [inline packages/blitz/src/cli/commands/install.ts:70]: Question: why "../../" ? I think we should start documenting these things, ad it's not clear why and where we do "../",  "../../", "../../../" etc.

**Review by beerose — APPROVED** [review]

File: packages/blitz/src/cli/commands/install.ts (hunk 1 above)
Comment (dillonraphael) [reply packages/blitz/src/cli/commands/install.ts:70]: Using the same method in other places to find the .blitz directory, then we go up a couple directories to find the package lockfile. I feel this way works best, especially for monorepos.
