### PR TITLE
Disable ink-spinner as a temporary measure

### LINKED ISSUE #2793: Spinner from `ink-spinner` causes `blitz install` to fail
### What is the problem?

blitz chakra-ui recipe seems to be broken. maybe a dependency update breaking part of the installer cli?

### Paste all your error logs here:

```
$ yarn blitz install chakra-ui

 # after hitting "enter" to continue......


ERROR  Cannot read property 'dots' of undefined

 .blitz/recipe-install/node_modules/ink-spinner/build/index.js:12:43

  9:  */
 10: const Spinner = ({ type = 'dots' }) => {
 11:     const [frame, setFrame] = react_1.useState(0);
 12:     const spinner = cli_spinners_1.default[type];
 13:     react_1.useEffect(() => {
 14:         const timer = setInterval(() => {
 15:             setFrame(previousFrame => {

 - Spinner (.blitz/recipe-install/node_modules/ink-spinner/build/index.js:12:43)
 -renderWithHoo (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconc
  s            iler.development.js:6036:18)
 -mountIndeterminateCo (.blitz/recipe-install/node_modules/react-reconciler/cjs/react
  ponent              -reconciler.development.js:8570:13)
 -beginWork$ (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconcile
            r.development.js:9938:16)
 -Object.invokeGuardedCal (.blitz/recipe-install/node_modules/react-reconciler/cjs/re
  backImpl               act-reconciler.development.js:11563:10)
 -invokeGuardedCall (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-re
  ack              conciler.development.js:11740:31)
 -beginWork$$ (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconcil
  1          er.development.js:15778:7)
 -performUnitOfW (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-recon
  rk            ciler.development.js:14696:12)
 -workLoopSyn (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-reconcil
  c          er.development.js:14669:22)
 -performSyncWorkOn (.blitz/recipe-install/node_modules/react-reconciler/cjs/react-re
  oot              conciler.development.js:14265:11)

✕ TypeError: Cannot read property 'dots' of undefined
✨  Done in 59.73s.
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.`yarn blitz install chakra-ui`

### Run `blitz -v` and paste the output here:

```
yarn blitz -v
yarn run v1.22.11
$ /Users/ta/twitter2arena/node_modules/.bin/blitz -v
macOS Big Sur | darwin-x64 | Node: v12.20.0

blitz: 0.40.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 110.34 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - /var/folders/cn/vz_lrgs56sz4vn49qy7680cm0000gn/T/yarn--1633293424484-0.775468713349567/node
    Yarn: 1.22.11 - /var/folders/cn/vz_lrgs56sz4vn49qy7680cm0000gn/T/yarn--1633293424484-0.775468713349567/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.1.1 => 3.1.1 
    blitz: 0.40.0 => 0.40.0 
    prisma: 3.1.1 => 3.1.1 
    react: alpha => 18.0.0-alpha-bdd6d5064-20211001 
    react-dom: alpha => 18.0.0-alpha-bdd6d5064-20211001 
    typescript: ~4.3 => 4.3.5 
```

### Please include below any other applicable logs and screenshots that show your problem:

_No response_

### PR DESCRIPTION
**Pull request by 9j**
#2793

(This is a temporary fix for this issue, so I just linked the issue. )

### What are the changes and their implications?

Temporarily fix ink-spinner's dependency issue on cli-spinner
I know this is not a good thing
However, it quickly restores important features. 

## Bug Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo](https://github.com/blitz-js/blitzjs.com))

### CODE REVIEW

File: packages/installer/src/executors/add-dependency-executor.tsx [hunk 1]
```diff
@@ -26,11 +27,12 @@ export function isAddDependencyExecutor(executor: ExecutorConfig): executor is C
 
 export const type = "add-dependency"
 
+// TODO: Once the dependency issue of ink-spinner is resolved, you should change "loading.." to <Spinner /> (https://github.com/blitz-js/blitz/issues/2793)
 function Package({pkg, loading}: {pkg: NpmPackage; loading: boolean}) {
   return (
     <Text>
       {`   `}
-      {loading ? <Spinner /> : "📦"}
+      {loading ? "loading.." : "📦"}
```
Comment (beerose) [inline packages/installer/src/executors/add-dependency-executor.tsx:35]:
```suggestion
      {loading ? "Loading..." : "📦"}
```

**Review by beerose — APPROVED** [review]

**Review by beerose — APPROVED** [review]
