### PR TITLE
Fix `blitz start -p 1234` not throwing an error if port 1234 is already in use

### LINKED ISSUE #624: Remove `--hostname` and `--port` from `blitz build`
### What is the problem?

The `blitz build` command current accepts `--hostname` and `--port` but these are invalid because blitz build does not start a server. It only compiles code.

Here's the file where these need to be removed from: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/build.ts

### LINKED ISSUE #630: When specifying a server port that's already in use, blitz will pick another port instead of throwing an error
### What is the problem?

When specifying a server port like `blitz start -p 4000`, blitz should throw an error instead of picking another port.

The automatic available port detection should only be used if a specific port is not specified by the user.

The offending line of code is here: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/next-utils.ts#L40

This will require a change to how we handle the `-p` argument which happens here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L17

Currently, `config.port` is always set, so `next-utils.ts` has no way to know whether to use automatic port detection or not.

So maybe we need to manually parse the input arguments here to see if the user specified a port or not: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L31

### Steps to Reproduce

1. Start a server on port 3000
2. `blitz start -p 3000` -> server started on 3001 instead of throwing an error

### Versions

```
0.12.0
```

### PR DESCRIPTION
**Pull request by ganeshmani**
This PR closes the issue of having `port` and `hostname` flags in `build` command. 

Closes #624 
Closes #630 

### What are the changes and their implications?

 it changes the build command in `cli/build`  by removing `port` and `hostname` flags. it also changes the `next-utils` in `server` config to accept `undefined` values for flags `port` and `hostname`, adding `non null assertion`

### Checklist

- [x] Tests added for changes
- [ ] User facing changes documented

### CODE REVIEW

File: packages/cli/src/commands/build.ts [hunk 1]
```diff
@@ -1,31 +1,14 @@
...
-      description: 'Set port number',
-      default: 3000,
-    }),
-    hostname: flags.string({
-      char: 'H',
-      description: 'Set server hostname',
-      default: 'localhost',
-    }),
-  }
-
```
Comment (flybayer) [inline packages/cli/src/commands/build.ts:21]: Good, this needed removed (unused)

File: packages/server/src/next-utils.ts [hunk 2]
```diff
@@ -37,10 +37,10 @@ export async function nextStartDev(
   config: ServerConfig,
 ) {
   const transform = createOutputTransformer(manifest, devFolder).stream
-  const availablePort = await detect({port: config.port, hostname: config.hostname})
+  const availablePort = await detect({port: config.port!, hostname: config.hostname!})
```
Comment (ryardley) [inline packages/server/src/next-utils.ts:40]: We don't know if port or hostname is set here. Probably a bit dangerous to use the non-null assertion operator (`!`). Be best if we check for undefined values and adjust accordingly or possibly tidy up the config to abstract away the differences between dev and build. Same as below

Comment (ganeshmani) [reply packages/server/src/next-utils.ts:40]: @ryardley got it. it makes sense it add a conditional declaration rather than using an assertion operator. I will make the change. Thanks for the feedback

**Comment by ganeshmani** [comment]
> Thanks for working on this!
> 
> However, even with this change, `config.port` will always be set because of `default: 3000` in `commands/start.ts`. And so automatic port detection still being used even when the user specifies a port.
> 
> So you need to make a change to `start.ts`, similar to how I describe in the original issue.
> 
> And I think also, the `availablePort` code should only be conditionally used if a port isn't specified.

@flybayer what happens if we run `blitz start` command without specifying port and hostname. for that, don't we need a default port and hostname for that?

**Comment by flybayer** [comment]
@ganeshmani we can simply let Next.js handle the defaults, so we don't have to worry about it

File: packages/server/src/next-utils.ts [hunk 3]
```diff
@@ -65,13 +77,31 @@ export function nextBuild(nextBin: string, cwd: string) {
...
+  return new Promise((res, rej) => {
+    if (availablePort && availablePort !== config.port) {
+      rej(`Couldn't start server on port ${config.port} ::port already in use`)
+    } else {
+      spawn(nextBin, spawnCommand, {
+        cwd,
+        stdio: 'inherit',
+      })
+        .on('exit', (code: number) => {
+          code === 0 ? res() : rej(`'next build' failed with status code: ${code}`)
```
Comment (ryardley) [inline packages/server/src/next-utils.ts:99]: This probably could be changed from `next build` to `next start`

Comment (ryardley) [inline packages/server/src/next-utils.ts:99]: Nice catch to add an exit handler.

File: packages/server/src/next-utils.ts [hunk 4]
```diff
@@ -65,13 +77,31 @@ export function nextBuild(nextBin: string, cwd: string) {
...
+
+  return new Promise((res, rej) => {
+    if (availablePort && availablePort !== config.port) {
+      rej(`Couldn't start server on port ${config.port} ::port already in use`)
+    } else {
+      spawn(nextBin, spawnCommand, {
+        cwd,
+        stdio: 'inherit',
+      })
+        .on('exit', (code: number) => {
```
Comment (ryardley) [inline packages/server/src/next-utils.ts:98]: Nice catch to add an exit hander!

File: packages/server/src/next-utils.ts [hunk 5]
```diff
@@ -65,13 +77,31 @@ export function nextBuild(nextBin: string, cwd: string) {
...
-  )
+  let spawnCommand: string[] = ['start']
+  let availablePort: number
+  if (config.port) {
+    availablePort = await detect({port: config.port})
+    spawnCommand = spawnCommand.concat(['-p', `${config.port}`])
+  }
+  if (config.hostname) {
+    spawnCommand = spawnCommand.concat(['-H', `${config.hostname}`])
+  }
```
Comment (ryardley) [inline packages/server/src/next-utils.ts:88]: There is an optional opportunity here to consolidate adding the port and hostname into a function that is shared between the start and dev functions.

**Comment by flybayer** [comment]
@ganeshmani awesome, this is looking good!

One last issue I see is that the availablePort is not being used.

1. Start a server on port 3000
2. Run `blitz start` and it will try to use port 3000 and then fail.

What should happen is this:

1. Start a server on port 3000
2. Run `blitz start` 
3. Blitz starts on next available port (3001 for example)

and this:

1. Start a server on port 3000
2. Run `blitz start -p 3000` 
3. Blitz fails to start

**Comment by ganeshmani** [comment]
> @ganeshmani awesome, this is looking good!
> 
> One last issue I see is that the availablePort is not being used.
> 
> 1. Start a server on port 3000
> 2. Run `blitz start` and it will try to use port 3000 and then fail.
> 
> What should happen is this:
> 
> 1. Start a server on port 3000
> 2. Run `blitz start`
> 3. Blitz starts on next available port (3001 for example)
> 
> and this:
> 
> 1. Start a server on port 3000
> 2. Run `blitz start -p 3000`
> 3. Blitz fails to start

Ah Okay. i thought we needed to fix that. https://github.com/blitz-js/blitz/issues/630

**Comment by flybayer** [comment]
`blitz start` should never throw an error.

`blitz start -p 3000` should throw an error if port 3000 is already in use

The original issue is that `blitz start -p 3000` did not throw an error.

That issue is fixed, but currently there's a regression with `blitz start` :)

**Comment by ganeshmani** [comment]
Got it. Let me fix that one. :-)

**Comment by ganeshmani** [comment]
@flybayer  Fixed. let me know if there is anything can be improved

**Comment by flybayer** [comment]
@ganeshmani sorry for the delay in testing this!

Unfortunately it's still not working right. Two problems:

1. Start another server on port 3000
2. Run `blitz start`.
3. ❌ What happens: Blitz starts on port 3000 (should start on port 3001)

.

1. Start another server on port 3000
2. Run `blitz start -p 3000`.
3. ❌ What happens: Blitz starts on port 3001 (should throw an error that port is in use)

**Comment by flybayer** [comment]
Thank you so much @ganeshmani!!
