### PR TITLE
Fix RPC routes on Windows

### LINKED ISSUE #299: [Windows] Blitz crashes after following initial build instructions
### What is the problem?
Installed blitz, setup a test project and am receiving the following error:
Module not found: Can't resolve 'child_process' in node_modules\@prisma\client\runtime' Could not find files for /projects in .next/build-manifest.json

### Steps to Reproduce: 
1.Created a new blitz application
2. Ran blitz start
3. Copied the schema from the documentation into schema.db
4. ran blitz db migrate and blitz generate all project
5. navigate to localhost:3000/projects and the app crashes with error:

Module not found: Can't resolve 'child_process' in node_modules\@prisma\client\runtime' Could not find files for /projects in .next/build-manifest.json

### Versions:
Windows 10 | win32-x64 | Node: v10.15.3

blitz: 0.7.0 (global)

### PR DESCRIPTION
**Pull request by wKovacs64**
### Type: bug fix 

Closes #299, #343

### What are the changes and their implications? :gear:

1. #423 forcefully excludes `@prisma/client` from the client bundle, but on Windows, it's `@prisma\client`. Updated the regex. That said, this shouldn't be needed at all (in terms of this particular issue). However, fixing it revealed Prisma client code was being shipped to the browser.
1. Why was Prisma code being run in the browser? Because queries and mutations were not being pulled out into SSR routes/files thanks to the ever-infuriating issue of the Windows path separator being different. Updated another regex and "slashified" the resolution path.

### Checklist

- [ ] Tests added for changes
- [ ] Any added terminal logging uses `packages/server/src/log.ts`

### Breaking change: no 

Quite the opposite, I hope!

### Other information

Tutorial project build before this change:

```
Page                            Size     First Load JS
┌ ○ /                           1.65 kB        80.3 kB
├   /_app                       273 B          60.8 kB
├ ○ /404                        2.58 kB        63.4 kB
├ ○ /projects                   1.18 kB        79.8 kB
├ ○ /projects/[id]              1.36 kB          80 kB
├ ○ /projects/[id]/edit         1.5 kB         80.2 kB
└ ○ /projects/new               793 B          79.5 kB
+ First Load JS shared by all   60.8 kB
  ├ static/pages/_app.js        273 B
  ├ chunks/commons.1334ac.js    10.6 kB
  ├ chunks/framework.329141.js  43.6 kB
  ├ runtime/main.c2ff6e.js      5.59 kB
  └ runtime/webpack.c21266.js   746 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

And after (matches macOS):

```
Page                                       Size     First Load JS
┌ ○ /                                      1.65 kB        80.4 kB
├   /_app                                  273 B          60.8 kB
├ ○ /404                                   2.58 kB        63.4 kB
├ λ /api/projects/mutations/createProject
├ λ /api/projects/mutations/deleteProject
├ λ /api/projects/mutations/updateProject
├ λ /api/projects/queries/getProject
├ λ /api/projects/queries/getProjects
├ ○ /projects                              1.03 kB        79.7 kB
├ ○ /projects/[id]                         1.32 kB          80 kB
├ ○ /projects/[id]/edit                    1.42 kB        80.1 kB
└ ○ /projects/new                          728 B          79.4 kB
+ First Load JS shared by all              60.8 kB
  ├ static/pages/_app.js                   273 B
  ├ chunks/commons.1334ac.js               10.6 kB
  ├ chunks/framework.329141.js             43.6 kB
  ├ runtime/main.c2ff6e.js                 5.59 kB
  └ runtime/webpack.c21266.js              746 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

### CODE REVIEW

File: packages/server/src/synchronizer/pipeline/rules/rpc/index.ts [hunk 1]
```diff
@@ -52,7 +53,7 @@ export const createRuleRpc: Rule = function configure({config: {src}}) {
 }
 
 export function isRpcPath(filePath: string) {
-  return new RegExp('(?:app\\/)(?!_rpc).*(?:queries|mutations)\\/.+').exec(filePath)
+  return /(?:app[\\/])(?!_rpc).*(?:queries|mutations)[\\/].+/.exec(filePath)
```
Comment (ryardley) [inline packages/server/src/synchronizer/pipeline/rules/rpc/index.ts:56]: Ha I like how the escape slash turns into the alternative char by adding a bracket 😄
