### PR TITLE
Fix #3745 Change ES6 import to require syntax

### LINKED ISSUE #3745: Codemod using import statement for `withBlitz` in `next.config.js`
### What is the problem?

When running the codemod, the `move the config from blitz.config.ts to next.config.js` step adds an import statement for `withBlitz` from `@blitzjs/next`.

But because `next.config.js` isn't parsed by babel, webpack or typescript it fails to run the app.

### Paste all your error logs here:

```
$ blitz dev
✔ Next.js was successfully patched with a React Suspense fix
Did not find custom config file
✔ Routes manifest was successfully generated
✔ Generated Prisma client
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
(node:69032) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
/Users/atrager/Nfinished/timerboard/next.config.js:1
import { withBlitz } from "@blitzjs/next";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
error Command failed with exit code 1.
```

### Paste all relevant code snippets here:

https://github.com/blitz-js/blitz/blob/main/packages/codemod/src/upgrade-legacy.ts#L94

### PR DESCRIPTION
**Pull request by siddhsuresh**
Closes: #3745
- [x] replace ```import { withBlitz } from "@blitzjs/next"``` to  ```const { withBlitz } = require("@blitzjs/next")```

### CODE REVIEW

File: packages/codemod/src/upgrade-legacy.ts [hunk 1]
```diff
@@ -90,8 +90,14 @@ const upgradeLegacy = async () => {
         },
       })
       let createdConfig = config.get().value.right
-
-      addNamedImport(program, "withBlitz", "@blitzjs/next")
+      let importWithBlitz = j.expressionStatement(
+        j.assignmentExpression(
+          "=",
+          j.identifier("const { withBlitz }"),
+          j.callExpression(j.identifier("require"), j.identifier("@blitzjs/next")),
```
Comment (dillonraphael) [inline packages/codemod/src/upgrade-legacy.ts:97]: I just tested this in astexplorer.net

I believe the second argument for `callExpression` should be an array. We also need to include quotes around `@blitzjs/next`.

This worked in astexplorer:

```ts
        let importWithBlitz = j.expressionStatement(
        j.assignmentExpression(
          "=",
          j.identifier("const { withBlitz }"),
          j.callExpression(j.identifier("require"), [j.identifier(`"@blitzjs/next"`)]),
        )
      )
```

**Review by dillonraphael — CHANGES_REQUESTED** [review]

File: packages/codemod/src/upgrade-legacy.ts (hunk 1 above)
Comment (siddhsuresh) [reply packages/codemod/src/upgrade-legacy.ts:97]: yeah my bad. Just tested it again.  I will update the code

Comment (dillonraphael) [reply packages/codemod/src/upgrade-legacy.ts]: Perfect. Thank you kind sir @siddhsuresh!

**Review by dillonraphael — APPROVED** [review]
